WebsiteDocs-4: Added the English `code-conduct.md` which was present …
apache/incubator-dolphinscheduler-website pull request #202
Opened 2020-10-21 11:31 UTC by IamMujuziMoses

…in Chinese but wasn't present in English and how to access it in 'development.js' file and how to access the Chinese version too

2020-10-21 11:32 UTC, IamMujuziMoses commented
This PR is associated to this main [issue]

[issue]: https://github.com/apache/incubator-dolphinscheduler/issues/3562

2020-10-24 10:04 UTC, CalvinKirs commented
@Segun-Ogundipe @Tianqi-Dotes PTAL.Thx

2020-10-25 15:15 UTC, Tianqi-Dotes requested changes
hi MujuziMoses,
I have reviewed the code-conduct.md doc, it is nice and I found some places not accurate from the original. please check those places.
Thanx
sincerely
Tianqi

2020-10-25 15:15 UTC, Tianqi-Dotes commented on docs/en-us/development/code-conduct.md
> + - **Easy to read** code is ambiguous, easy to read and understand, when debugging one knows the intent of the code.
the word ambiguous
differ from the original doc
maybe use clear nonambiguous obvious plain unambiguous unequivocal accurate instead

2020-10-25 15:15 UTC, Tianqi-Dotes commented on docs/en-us/development/code-conduct.md
> + - Use Checkstyle to check your code for special reasons for violating validation rules. The template location is located at ds_check_style.xml.
didn't mention this file is under the root directory

2020-10-25 15:15 UTC, Tianqi-Dotes commented on docs/en-us/development/code-conduct.md
> + - Profiles are named in camelCase, and file names are lowercase.
ambiguous meaning in 2 parts.
the word 'Profiles'  maybe change to the 'configuration file' would be more accurate
'and file names are lowercase.' didn't mention the initial letter should be lowercase.

2020-10-25 15:15 UTC, Tianqi-Dotes commented on docs/en-us/development/code-conduct.md
> + - Priority is given to `LinkedList` and only use `ArrayList` if you need to get element values in the collection.
didn't mention get element values through index when using ArrayList.

2020-10-25 15:15 UTC, Tianqi-Dotes commented on docs/en-us/development/code-conduct.md
> +   - Automatic : Unit tests should be fully automated, not interactive. Manual checking of output results is prohibited, `System.out`, `log`, etc. are not allowed, and must be verified with assertion
try to fix space after the  word Automatic

2020-10-25 15:15 UTC, Tianqi-Dotes commented on docs/en-us/development/code-conduct.md
> +   - Independent : It is prohibited to call each other between unit test cases and to rely on the order of execution. Each unit test can be run independently.
try to fix space after the  word Independent

2020-10-25 15:15 UTC, Tianqi-Dotes commented on docs/en-us/development/code-conduct.md
> +   - Repeatable : Unit tests cannot be affected by the external environment and can be repeated.
try to fix space after the word Repeatable

2020-10-25 15:15 UTC, Tianqi-Dotes commented on docs/en-us/development/code-conduct.md
> +   - Border (Boundary value test) : The expected results are obtained by entering the boundaries of loop boundaries, special values, data order, etc.
try to fix space after the )

2020-10-25 15:15 UTC, Tianqi-Dotes commented on docs/en-us/development/code-conduct.md
> +   - Each line is no longer than `200` in length, ensuring that each line is semanticly complete for easy understanding.
wrong spelling word semanticly

2020-10-25 15:44 UTC, IamMujuziMoses commented
@Tianqi-Dotes sure thing, thanks for the review, let me get working on those

2020-10-25 23:49 UTC, CalvinKirs commented
Hi, please resolve the conflict..

2020-10-26 09:25 UTC, dailidong commented
> Hi, please resolve the conflict..

I have solved this conflict file because it's the first contribution by @IamMujuziMoses

2020-10-26 09:25 UTC, merged

2020-10-26 09:25 UTC, dailidong reviewed
+1 
good job