translate task-structure into en-us
apache/incubator-dolphinscheduler-website pull request #263
Opened 2021-01-14 15:11 UTC by Tianqi-Dotes

translate task-structure into en-us

2021-01-15 02:11 UTC, CalvinKirs commented
@ptyp @Segun-Ogundipe PTAL.Thx

2021-01-15 14:08 UTC, Segun-Ogundipe requested changes
Hi @Tianqi-Dotes, great job on this PR. I left some comments here.

Regards.

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-15 14:08 UTC, Segun-Ogundipe commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order|parameter name||type|description |notes
`order` should be `No.`

2021-01-17 13:31 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +Dolphinscheduler persists all created tasks in the table 't_ds_process_definition'.
done

2021-01-17 13:32 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +order | field  | type  |  description
done all replacemnets

2021-01-17 13:35 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +2|name|varchar(255)|define workflow name
done

2021-01-17 13:36 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +3|version|int(11)|define workflow version
done

2021-01-17 13:37 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +4|release_state|tinyint(4)|define workflow publish status：0 not yet launch, 1 launched
done

2021-01-17 13:38 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +6|user_id|int(11)|define workflow owner id
done

2021-01-17 13:43 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +7|process_definition_json|longtext|define workflow JSON
done

2021-01-17 13:44 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +8|description|text|define workflow description
done

2021-01-17 13:45 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +10|flag|tinyint(4)|specify workflow availability：0 not available, 1 available
done

2021-01-17 13:47 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +11|locations|text|node location info
done

2021-01-17 13:49 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +19|modify_by|varchar(36)|specify users make modification
done

2021-01-17 13:52 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +In which 'process_definition_json' is the core field, defines task info in DAG and is stored in JSON format.
done

2021-01-17 13:54 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +Following table describes the common data structure
done

2021-01-17 13:58 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +2|tasks|Array|task collections in the workflow[structures of each task type please check following sections]
done

2021-01-17 14:03 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +# Detailed Explanation About the Storage Structure of Each Task Type
done

2021-01-17 14:05 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +Execute query/update SQL to specified datasource.
done

2021-01-17 14:09 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +**Node data structure as follow:**
done all replacement

2021-01-17 14:10 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +7| |sql |String |query SQL sentence
done

2021-01-17 14:10 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +8| |udfs | String| udf functions|specify UDF function id, separate by comma
done

2021-01-17 14:11 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +9| |sqlType | String| SQL node type |0 for query and 1 for none query SQL
done

2021-01-17 14:12 UTC, Tianqi-Dotes commented on docs/en-us/1.3.4/user_doc/task-structure.md
> +**Node data structure as follow:**
done

2021-01-17 14:13 UTC, Tianqi-Dotes commented
@Segun-Ogundipe  Hi, Segun
Deeply thanx for reviewing. Have done all the changes.
Best wishes
Tianqi

2021-01-17 14:20 UTC, CalvinKirs approved these changes
LGTM

2021-01-17 14:20 UTC, merged